# Kargos-Backend Server
# Before you apply this deployment, you must first deploy the Kargos-agent in the form of daemonset and Kargos-Database

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: royroyee/kargos:latest
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 9000