# Kargos-Database
# Kargos uses MongoDB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017

#The Kargos's database stores and deletes data periodically. We judged that there is no need to set the volume of data stored by Kargos.
#It's your choice.

          # volumeMounts:
          #   - name: mongodb-data
          #     mountPath: /data/db
  # volumeClaimTemplates:
  #   - metadata:
  #     name: mongodb-data
  #     annotations:
  #       volume.beta.kubernetes.io/storage-class: standard
  #     spec:
  #       accessModes: [ "ReadWriteOnce" ]
  #       resources:
  #         requests:
  #           storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None