apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      name: http
  selector:
    app: backend
  type: LoadBalancer